### ISSUE TITLE
Fail to import package after pip install

### ISSUE THREAD

**Issue by gperakis** [Microsoft/BlingFire#10]
Hello there, 

Just pip installed the Blingfire in Linux Ubuntu 14.04. 

Tried to import the package and I'm getting this traceback. 

Any ideas on what goes wrong?

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/---/Programs/pycharm-2017.1/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/---/envs/py36env/lib/python3.6/site-packages/blingfire/__init__.py", line 16, in <module>
    blingfiretokdll = cdll.LoadLibrary(os.path.join(path, "libblingfiretokdll.so"))
  File "/usr/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/---/envs/py36env/lib/python3.6/site-packages/blingfire/libblingfiretokdll.so: symbol _ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

**Comment by SergeiAlonichau** [comment]
This is libc incompatibility, the *.so image was compiled on ubuntu 16.04. 

The work around is to recompile all from source with cmake under yor operating system (14.04) and replace locally libblingfiretokdll.so with the one you get after the compilation.  Please compile release version, debug is significantly slower.

Any suggestion how to handle it properly?

**Comment by JiguangShen** [comment]
Maybe try to ungrade your GCC

**Comment by SergeiAlonichau** [comment]
I published 0.0.9 package with SO compiled on 14.04 which comes with older C++ libraries. It should work now on both 14.04, 16.04 and 18.04.
