### ISSUE TITLE
Which vocab file you are using for xlm_roberta_base

### ISSUE THREAD

**Issue by hhdd92** [microsoft/BlingFire#108]
Could you share the vocab file that for xlm_roberta_base? We are trying to convert Id to tokens. Thank you.

**Comment by SergeiAlonichau** [comment]
https://raw.githubusercontent.com/microsoft/BlingFire/master/ldbsrc/xlm_roberta_base/spiece.model.exportvocab.txt

**Comment by SergeiAlonichau** [comment]
The sources as well readme(s) how bin files are created are under ldbsrc directory, in this case see https://github.com/microsoft/BlingFire/tree/master/ldbsrc/xlm_roberta_base .

**Comment by hhdd92** [comment]
Thank you!
