### ISSUE TITLE
East Asian support

### ISSUE THREAD

**Issue by justinormont** [microsoft/BlingFire#11]
The readme says, "Currently released model supports most of the languages except East Asian (Chinese Simplified, Traditional, Japanese, Korean, Thai)."

Is East Asian support on the roadmap?

This could be useful for [ML.NET](https://github.com/dotnet/machinelearning/), where only a whitespace tokenizer has been open sourced. One potential issue is ML.NET has a preference for pure C# code. 

The whitespace tokenization (or breaking on any specific character) is not suitable for East Asian languages: https://github.com/dotnet/machinelearning/issues/325

**Comment by SergeiAlonichau** [comment]
Yes, this is on our list. We don't have a concrete ETA yet.
