### ISSUE TITLE
Cannot find "no_padding" option in C# ?

### ISSUE THREAD

**Issue by stephane-lallee** [microsoft/BlingFire#127]
Hey @SergeiAlonichau and @ankane, I'm trying to get parity with HuggingFace tokeniser from the BlingFire C# bindings:
```
    public int[] TestTokenise(string input_str)
    {
        string tokeniserModelPath = "D:/Models/tokenizers/gpt2.bin";
        tokenizerHandle = BlingFireUtils.LoadModel(tokeniserModelPath);
        BlingFireUtils.SetNoDummyPrefix(tokenizerHandle, false);
        Debug.Log($"About to tokenize {input_str}");
        byte[] inBytes = System.Text.Encoding.UTF8.GetBytes(input_str);
        int[] ids = new int[128];
        int outputCount = BlingFireUtils.TextToIds(tokenizerHandle, inBytes, inBytes.Length, ids, ids.Length, 0);
        Debug.Log($"Found {outputCount} tokens [{string.Join(",",ids)}]");
        return ids.Take(outputCount).ToArray();
    }
```
I'm getting different tokens than what @ankane had earlier: 
![image](https://user-images.githubusercontent.com/6750632/135237532-8bdeb4ee-c46b-438e-912e-2857dd677076.png)

From your discussion, I think I'd need to set no_padding to true, but I do not find this option in the C# interface. Any clue where I should look?

_Originally posted by @stephane-lallee in https://github.com/microsoft/BlingFire/issues/82#issuecomment-929989834_

**Comment by SergeiAlonichau** [comment]
you need to resize the ids array down to outputCount elements, see C# example: https://github.com/microsoft/BlingFire/blob/master/nuget/test/Program.cs .

            var outputCount = BlingFireUtils.TextToIds(h1, inBytes, inBytes.Length, Ids, Ids.Length, 0);
            Console.WriteLine(String.Format("return length: {0}", outputCount));
            if (outputCount >= 0)
            {
                Array.Resize(ref Ids, outputCount);
                Console.WriteLine(String.Format("return array: [{0}]", string.Join(", ", Ids)));
...

Python API's have this parameter, but not C#.

**Comment by stephane-lallee** [comment]
Hey @SergeiAlonichau !
Thanks for helping on this. Then the culprit is not this parameter, I thought no_padding was doing something else.
The problem is that the non-zero ids I'm getting from Transformers are different than the ones I'm getting from BlingFire:

```
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("gpt2")
sequence = "This is a test. Another test."
input_ids = tokenizer.encode(sequence, add_special_tokens=False)
print(input_ids)
```
Output --> [1212, 318, 257, 1332, 13, 6023, 1332, 13]

While from BlingFire the output I get with this code is:
```
var tokenizerHandle = BlingFireUtils.LoadModel("D:/Models/tokenizers/gpt2.bin");
BlingFireUtils.SetNoDummyPrefix(tokenizerHandle, false);
byte[] inBytes = System.Text.Encoding.UTF8.GetBytes(input_str);
int[] ids = new int[128];
int outputCount = BlingFireUtils.TextToIds(tokenizerHandle, inBytes, inBytes.Length, ids, ids.Length, 0);
Debug.Log($"[{string.Join(",",ids)}]");
```
Output --> [770, 318, 257, 1332, 13, 6023, 1332, 13, 0, 0, 0, ....]

**Comment by SergeiAlonichau** [comment]
Use this API after the model is loaded 
 https://github.com/microsoft/BlingFire/blob/d9d5cea9cb7f5abbe650ef348c4010dce0658043/nuget/lib/BlingFireUtils.cs#L221 to control if a special space added in front of the input or not, this corresponds to : **add_prefix_space=True/False** from Huggingface tokenizers.

```python
AutoTokenizer.from_pretrained("roberta-base", add_prefix_space=True/False)
```
