### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [microsoft/BlingFire#13]
I would like to point out that an identifier like “[`_FA_BRRESULTCA_H_`](https://github.com/Microsoft/BlingFire/blob/82f0e58d8dd9a6d4ab81a7c7a8cae129ba9172ce/blingfireclient.library/inc/FABrResultCA.h#L8 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by SergeiAlonichau** [comment]
Thank you for pointing it out. We will fix it.

**Comment by SergeiAlonichau** [comment]
Also sorry if I misunderstood your intent, feel free to provide a pull request if you want so.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?
