### ISSUE TITLE
Error loading files with paths with non-ANSI characters

### ISSUE THREAD

**Issue by DavidObando** [microsoft/BlingFire#136]
We're using BlingFire from C#, using BlingFireNuget version 0.1.8. Our product is running on Windows, on an NTFS file system. We cannot load model files that contain special non-ANSI characters in the path (such as `ä` in the user's name), for example: `C:\Users\UserNäme\AppData\Local\Microsoft\VisualStudio\17.0_d1920296\IntelliCodeModels\all_line-completions2_ExtractedData\bpe.bin` will fail to load even though it would succeed if the path didn't contain the `ä` character.

BlingFireUtils.LoadModel(string modelName) converts the string to a UTF-8 encoded byte array to be passed to the extern "C" implementation `void* LoadModel(const char * pszLdbFileName)`. Somewhere inside it's failing and in the .NET side we get an error that reads:
```
System.Runtime.InteropServices.SEHException: External component has thrown an exception.
      at BlingFire.BlingFireUtils.LoadModel(Byte[] modelName)
      ...
```
We've tried encoding the model file name using Unicode (UTF-16) and ANSI, both fail the same as the default UTF-8 encoding, all with the same result. Note that NTFS file systems encode paths in a format close to UTF-16.

It looks like the call to [fopen_s to read the model file](https://github.com/microsoft/BlingFire/blob/a0fa2808230c8e5e277bec520e91a36680202091/blingfireclient.library/src/FAImageDump.cpp#L97) is not going to allow for files with `ä` in the file path and could be replaced by a call to [_wfopen_s instead](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fopen-s-wfopen-s?view=msvc-170). This change would also require BlingFireUitls.LoadModel to switch from UTF-8 encoding to UTF-16 encoding, but I might be wrong.

**Comment by SergeiAlonichau** [comment]
Hi David

The solution might be to **add** one more Load function that takes wchar_t name as input. Feel free to prepare a PR for this.

Also as described here https://stackoverflow.com/questions/23285759/fopen-file-name-with-utf8-string-in-windows you can try getting a short file name for your file name and feed that.

I am not sure if setting locale to UTF-8 (setlocale(LC_ALL, ".65001");) would make it work as well with UTF-8 string passed as a file name.

An alternative solution can be to take a path as UTF-8 string (as a super set of ASCII) and if there are any non ascii bytes then convert it to wchat_t (utf16le ?) string and use the _wfopen_s under the hood.

Thank you!

**Comment by DavidObando** [comment]
The approach described in https://stackoverflow.com/questions/23285759/fopen-file-name-with-utf8-string-in-windows worked well for us. We're now only sending short path names to BlingFire, which works well for all our supported scenarios.

If I find any shortcomings that require us to add a wide character Load function I'll prepare a PR. For now I'll close this issue.

Thank you!
