### ISSUE TITLE
Does it support Chinese or Japanese

### ISSUE THREAD

**Issue by loveJasmine** [microsoft/BlingFire#19]

**Comment by SergeiAlonichau** [comment]
Hi, the library is language agnostic, it supports Chinese, Japanese and all languages as long as they are covered by Unicode charset. Currently as of May 1 2020, the library supports 4 tokenization algorithms:

1. rule based tokenization (like NLTK) preserving or breaking Chinese characters apart
2. wordpiece algorithm used in various BERT models (you can provide you own list of segments)
3. sentencepiece Unigram LM algorithm (like the one used in XLNET)
4. sentencepiece BPE algorithm
