### ISSUE TITLE
Link to wrappers in other languages in the README

### ISSUE THREAD

**Issue by mcobzarenco** [microsoft/BlingFire#24]
I wrote a Rust [wrapper](https://github.com/reinfer/blingfire-rs) for the library -- I was curious if there's any intention to link to "unoffical" wrappers in other languages in the README.

**Comment by SergeiAlonichau** [comment]
Sorry I am getting to your comment so late. I will add a link to the readme file. We don't have any official way to do it. Your suggestions are welcome! Feel free to modify the readme file and send a pull request yourself next time.
