### ISSUE TITLE
Add support for XLnet

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/BlingFire#30]
You just merged support for BERT it seems, which is nice; but [XLnet](https://github.com/zihangdai/xlnet) is the new state of the art and has a big momentum, it would be nice to include it.

Just by curiosity, will you use BERT internally for improving BING search results? (if you cannot disclose this information, that's OK!)

**Comment by SergeiAlonichau** [comment]
Please use this manual to create support for XLNet: https://github.com/Microsoft/BlingFire/wiki/How-to-add-a-new-BERT-tokenizer-model , I will be happy to help.

**Comment by LifeIsStrange** [comment]
@SergeiAlonichau
That would be an honor, but currently I have not enough knowledge in deep learning. 
I plan to use tools like BlingFire after having studied NLP. 
It would be better if someone more knowledgeable than me did this.

**Comment by SergeiAlonichau** [comment]
I have just checked in the xlnet model, which uses unigram lm segmentation based on sentence piece library. Our implementation already has a good parity and good performance but this is still work in progress. We plan to publish it by the end of April.

**Comment by SergeiAlonichau** [comment]
It is done! We have published a new python package v 0.1.1 which has XLNET support in two ways:
1. xlnet.bin has relevant NFKC normalization and segmentation
2. xlnet_nonorm.bin does not have NFKC normalization (it assumes the text is already normalized) and only has segmentation

Both models have ~99.9% parity on input level comparing with the sentence piece library implementation, see corresponding readme.txt files in the BlingFire/ldbsrc/xlnet  and  BlingFire/ldbsrc/xlnet_nonorm directories.

**Comment by ankane** [comment]
Thanks @SergeiAlonichau! What do you think about tagging the latest release? This should make it easier to find/reference a specific release on GitHub.
