### ISSUE TITLE
Ruby Library

### ISSUE THREAD

**Issue by ankane** [microsoft/BlingFire#46]
Hi, thanks for this awesome library! I wanted to let you know there are now [Ruby bindings](https://github.com/ankane/blingfire) for it. A few notes:

- When calling `LoadModel` with a path that doesn't exist, an uncaught exception is raised that crashes the program (`libc++abi.dylib: terminating with uncaught exception`). It'd be great to catch this and have a method to retrieve the error.
- It includes a shared library for Mac. I was able to get it to compile with a few changes: https://github.com/microsoft/BlingFire/compare/master...ankane:mac (#9)
- It'd be great if there were tagged releases on GitHub. It currently compiles shared libraries from master (with [this repo](https://github.com/ankane/ml-builds)).

If you have any feedback, let me know or feel free to create an issue on the project. Thanks!

**Comment by SergeiAlonichau** [comment]
Thank you for the suggestions! I will look into fixing the loadlibrary and adding tagged releases.

**Comment by ankane** [comment]
Thanks for tagging (easier to reference a specific version of code, and users can now get release notifications from GitHub) 🎉

**Comment by ankane** [comment]
Going to close since just wanted to announce the library here. 2/3 suggestions were added (I really appreciate it!), so can file a new issue for the last one if it's something you're considering.
