### ISSUE TITLE
Support for GPT-2, RoBERTa, and general Hugging Face models

### ISSUE THREAD

**Issue by ankane** [microsoft/BlingFire#82]
Hi, thanks for this great library! I'm trying to add GPT-2 but am having trouble. The model compiles, but only returns a single unknown token when testing it.

Model code: https://github.com/microsoft/BlingFire/compare/master...ankane:gpt2
Model type: BPE

Test code

```py
import blingfire

h = blingfire.load_model("gpt2.bin")
print(blingfire.text_to_ids(h, "This is a test", 128, 100))
# outputs [100   0   0  ...]
```

If you have time, any advice would be great (I'm having trouble understanding how it works).

Edit: fwiw, I was able to build a model for [T5](https://github.com/google-research/text-to-text-transfer-transformer), but had a SentencePiece model to start from.

**Comment by ankane** [comment]
A more general question is how to train a model from the vocab and merges files from Hugging Face Transformers, like [these](https://huggingface.co/gpt2#list-files).

Building ones from SentencePiece models works great (have been able to build T5, Reformer, and Pegasus).

**Comment by ankane** [comment]
Quick update: have made some progress with RoBERTa and GPT-2.

- BlingFire output: `[152, 16, 10, 1296, 4, 2044, 1296, 4, 0, 0, 0, ...]`
- Transformers output: `[0, 713, 16, 10, 1296, 4, 2044, 1296, 4, 2]`

Transformers adds special tokens - `<s>` (0) at start and `</s>` (2) at the end - so it seems to match except for the first token (152 vs 713).

Model code: https://github.com/microsoft/BlingFire/compare/master...ankane:gpt2

Test code

```python
import blingfire

h = blingfire.load_model("roberta.bin")
print(blingfire.text_to_ids(h, "This is a test. Another test.", 20, 100))
```

```python
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("roberta-base")
print(tokenizer("This is a test. Another test.")["input_ids"])
```

**Comment by SergeiAlonichau** [comment]
Hi, 

First of all thank you for the great progress and so sorry for missing this Issue you have openned.

The trailing 0-s should not be an issue, it is just a padding ids . If you call it with no_padding=True 
 ids = text_to_ids(h, line, max_length, unk, True)  then it should not have trailing 0's.

Could you please create a PR with the model and I can help run the parity test vs original model and weed out the differences?

**Comment by SergeiAlonichau** [comment]
> A more general question is how to train a model from the vocab and merges files from Hugging Face Transformers, like [these](https://huggingface.co/gpt2#list-files).
> 
> Building ones from SentencePiece models works great.
> 
> Name	Type	Works	Link
> T5	SentencePiece	✓	https://huggingface.co/t5-base#list-files
> Reformer	SentencePiece	✓	https://huggingface.co/google/reformer-crime-and-punishment#list-files
> Pegasus	SentencePiece	✓	https://huggingface.co/google/pegasus-xsum#list-files
> RoBERTa	BPE		https://huggingface.co/roberta-base#list-files
> GPT-2	BPE		https://huggingface.co/gpt2#list-files

Well, we might need to adjust the algorithm a little bit, right now I don't quite understand it, I need to see how the merges and vocab are used. In sentence piece bpe there is only one vocab which is merges at the same time. Quickly looking at the vocab.json and merges.txt does not explain it for me. If you could describe the algorithm or there is a description somewhere it would help, otherwise I will read the sources.

**Comment by SergeiAlonichau** [comment]
Ok, I think I get it now... looks like they add a bunch of symbols in the beginning otherwise the merges.txt ranks and the vocab.json ids do match so looks like we should not need both of them. I will get model sources from your master branch and see the parity.

**Comment by ankane** [comment]
Thanks for taking a look @SergeiAlonichau

**Comment by SergeiAlonichau** [comment]
I have made an initial change to support gpt2, I will test tomorrow how it works on roberta. Could you please help review the code chage: https://github.com/microsoft/BlingFire/pull/96

**Comment by SergeiAlonichau** [comment]
This pull request adds roberta https://github.com/microsoft/BlingFire/pull/97 . Ir was more work with it because they separately use merges.txt for merge order and vocab.json to for token to ID map. I will do parity testing and then publish new packages.

**Comment by ankane** [comment]
Big thanks @SergeiAlonichau!! This is great. Seeing the same results between Bling Fire and Transformers (with `add_prefix_space=True`) with both GPT-2 and RoBERTa.

```python
import blingfire
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("roberta-base", add_prefix_space=True)
print(tokenizer("This is a test. Another test.", add_special_tokens=False)["input_ids"])

h = blingfire.load_model("ldbsrc/ldb/roberta.bin")
print(list(blingfire.text_to_ids(h, "This is a test. Another test.", 20, no_padding=True)))
```

Is there a way for Bling Fire to match the Transformers output with `add_prefix_space=False` (this is the default for Transformers and changes the first token)?

Also, fwiw, needed to rebuild `libblingfiretokdll.dylib` to get it working on Mac.

**Comment by SergeiAlonichau** [comment]
I have rebuilt the Windows and Mac versions, so it should start working on Mac. 

As for add space difference, some more testing is needed it will take more time, I will look into it...

**Comment by ankane** [comment]
Thanks @SergeiAlonichau, just updated the Ruby library to 0.1.5 and both models are working great!

**Comment by ankane** [comment]
Awesome, thanks @SergeiAlonichau!

**Comment by stephane-lallee** [comment]
Hey @SergeiAlonichau and @ankane, I'm trying to get parity with HuggingFace tokeniser from the BlingFire C# bindings:
```
    public int[] TestTokenise(string input_str)
    {
        string tokeniserModelPath = "D:/Models/tokenizers/gpt2.bin";
        tokenizerHandle = BlingFireUtils.LoadModel(tokeniserModelPath);
        BlingFireUtils.SetNoDummyPrefix(tokenizerHandle, false);
        Debug.Log($"About to tokenize {input_str}");
        byte[] inBytes = System.Text.Encoding.UTF8.GetBytes(input_str);
        int[] ids = new int[128];
        int outputCount = BlingFireUtils.TextToIds(tokenizerHandle, inBytes, inBytes.Length, ids, ids.Length, 0);
        Debug.Log($"Found {outputCount} tokens [{string.Join(",",ids)}]");
        return ids.Take(outputCount).ToArray();
    }
```
I'm getting different tokens than what @ankane had earlier: 
![image](https://user-images.githubusercontent.com/6750632/135237532-8bdeb4ee-c46b-438e-912e-2857dd677076.png)

From your discussion, I think I'd need to set no_padding to true, but I do not find this option in the C# interface. Any clue where I should look?

**Comment by SergeiAlonichau** [comment]
> Hey @SergeiAlonichau and @ankane, I'm trying to get parity with HuggingFace tokeniser from the BlingFire C# bindings:
> 
> ```
>     public int[] TestTokenise(string input_str)
>     {
>         string tokeniserModelPath = "D:/Models/tokenizers/gpt2.bin";
>         tokenizerHandle = BlingFireUtils.LoadModel(tokeniserModelPath);
>         BlingFireUtils.SetNoDummyPrefix(tokenizerHandle, false);
>         Debug.Log($"About to tokenize {input_str}");
>         byte[] inBytes = System.Text.Encoding.UTF8.GetBytes(input_str);
>         int[] ids = new int[128];
>         int outputCount = BlingFireUtils.TextToIds(tokenizerHandle, inBytes, inBytes.Length, ids, ids.Length, 0);
>         Debug.Log($"Found {outputCount} tokens [{string.Join(",",ids)}]");
>         return ids.Take(outputCount).ToArray();
>     }
> ```
> 
> I'm getting different tokens than what @ankane had earlier: ![image](https://user-images.githubusercontent.com/6750632/135237532-8bdeb4ee-c46b-438e-912e-2857dd677076.png)
> 
> From your discussion, I think I'd need to set no_padding to true, but I do not find this option in the C# interface. Any clue where I should look?

Stephanie, did you figure this out?  Could you please see this reply https://github.com/microsoft/BlingFire/issues/113#issuecomment-932434671 .
