### ISSUE TITLE
Convert SentencePiece Model to BlingFire.

### ISSUE THREAD

**Issue by overwindows** [microsoft/BlingFire#85]
Is there a way to convert a existing SentencePiece model to BlingFire format?

**Comment by smbecker** [comment]
This looks like a suitable sample on how to convert a SentencePiece sample: https://github.com/microsoft/BlingFire/tree/master/ldbsrc/xlnet

**Comment by theoqian** [comment]
In the example above, spm_export_vocab is used to convert a sentencepiece model into vocabulary file. However could you find this script in the repo?
