### ISSUE TITLE
Calling LoadModel from .net core WebAPI throws SEHException

### ISSUE THREAD

**Issue by gluckez** [microsoft/BlingFire#86]
exception:
`   at BlingFire.BlingFireUtils.LoadModel(Byte[] modelName)
   at BlingFire.BlingFireUtils.LoadModel(String modelName) in C:\Users\vanac\.nuget\packages\blingfirenuget\0.1.4\contentFiles\cs\any\BlingFireUtils.cs:line 23`

The same code was tested with unit tests and works perfectly. It only throws the exception when i send a request to a webAPI using the same component. (this behaviour is the same for running the api through IIS as well as running it directly.)

EDIT: code causing this issue:
`public TextTokenizer()
        {
            _EncoderModel = BlingFireUtils.LoadModel("./bert_base_tok.bin");
        }`

**Comment by gluckez** [comment]
Update: The fault was mine. when running in a webApi, the application runs in a workingdirectory different from where the assembly is located, which caused it to not find the file, but the exception didn't really tell me much. I consider this closed.

**Comment by SergeiAlonichau** [comment]
There was a long lasting feature request, that API should not throw the exception and rather return an error code. My apologies it is still not done... if you want feel free to take on this task :-) though.
