### ISSUE TITLE
macOS support, and Python dependencies

### ISSUE THREAD

**Issue by mvasilkov** [microsoft/BlingFire#9]
Hi all, these are two related issues:

1. After running `pip3 install blingfire` in macOS, which appears to work fine, it's impossible to use the library since the .dylib isn't there. And the error message is rather meh: `AttributeError: 'NoneType' object has no attribute 'TextToWords'`

2. It appears to require NumPy, but doesn't specify it as a dependency, so running from a venv without numpy in it also fails.

Both can be fixed by tuning the setup.py metadata, but wrt macOS, can we please actually support it? I can't imagine it being very different from the Linux build, if at all.

Thanks for open sourcing this!

**Comment by jialigit** [comment]
I also find this problem of not supporting macOs platform. Really hope for the open source of it.

**Comment by SergeiAlonichau** [comment]
Looking into it.

**Comment by ma2rten** [comment]
Same problem:

> $ python3 -m virtualenv env
> Using base prefix '/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7'
> /Users/bosma/Library/Python/3.7/lib/python/site-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
>   import imp
> New python executable in /Users/bosma/projects/env/bin/python3.7
> Also creating executable in /Users/bosma/projects/env/bin/python
> Installing setuptools, pip, wheel...done.
> $ source env/bin/activate
> $ pip install pip install blingfire
> Requirement already satisfied: pip in ./env/lib/python3.7/site-packages (19.1.1)
> Collecting install
>   ERROR: Could not find a version that satisfies the requirement install (from versions: none)
> ERROR: No matching distribution found for install
> $ pip install blingfire
> Collecting blingfire
>   Downloading https://files.pythonhosted.org/packages/6b/aa/f999e3ca3e826cbdefe7dea7f90baf06db26448ef4cfd80f4800d84d660f/blingfire-0.0.9-py3-none-any.whl (248kB)
>      |████████████████████████████████| 256kB 1.5MB/s 
> Installing collected packages: blingfire
> Successfully installed blingfire-0.0.9
> $ python
> Python 3.7.0 (default, Aug 17 2018, 21:14:48) 
> [Clang 9.1.0 (clang-902.0.39.2)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from blingfire import *
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/bosma/projects/env/lib/python3.7/site-packages/blingfire/__init__.py", line 5, in <module>
>     import numpy as np
> ModuleNotFoundError: No module named 'numpy'
> >>> text = 'This is the Bling-Fire tokenizer'
> >>> output = text_to_words(text)
> KeyboardInterrupt
> >>> 
> $ pip install numpy
> Collecting numpy
>   Downloading https://files.pythonhosted.org/packages/43/6e/71a3af8680a159a141fab5b4d19988111a09c02ffbfdeb42175cca0fa341/numpy-1.16.3-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
>      |████████████████████████████████| 13.9MB 2.1MB/s 
> Installing collected packages: numpy
> Successfully installed numpy-1.16.3
> $ python
> Python 3.7.0 (default, Aug 17 2018, 21:14:48) 
> [Clang 9.1.0 (clang-902.0.39.2)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from blingfire import *
> >>> text = 'This is the Bling-Fire tokenizer'
> >>> output = text_to_words(text)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/bosma/projects/env/lib/python3.7/site-packages/blingfire/__init__.py", line 58, in text_to_words
>     o_len = blingfire.TextToWords(c_char_p(s_bytes), c_int(len(s_bytes)), byref(o_bytes), c_int(o_bytes_count))
> AttributeError: 'NoneType' object has no attribute 'TextToWords'
> >>> 
>

**Comment by sandeepeecs** [comment]
> I also find this problem of not supporting macOs platform. Really hope for the open source of it.

Any suggested fixes to make it work no macOS ?

**Comment by sandeepeecs** [comment]
> Looking into it.

Any suggested fixes to make it work no macOS?

**Comment by ZPVIP** [comment]
there is no mac OS support:
https://github.com/microsoft/BlingFire/blob/52a5d30d532ba7aebfe9325a58a53bb0247556d2/scripts/blingfiretok.py#L14

**Comment by ankane** [comment]
fwiw, I was able to get it working on Mac with the following changes: https://github.com/microsoft/BlingFire/compare/master...ankane:mac. There's probably a cleaner way to do it.

**Comment by SergeiAlonichau** [comment]
Thank you,  I will look at it today.

**Comment by SergeiAlonichau** [comment]
Thank you, Andrew, for doing the change!

Starting from version 0.0.16 blingfire package supports Mac.

**Comment by ankane** [comment]
Awesome, thanks @SergeiAlonichau!
