### ISSUE TITLE
Bert-like tokenization model compilation not finishing

### ISSUE THREAD

**Issue by RobertGengiu** [microsoft/BlingFire#92]
Hi all,

I am trying to compile this model [https://huggingface.co/sentence-transformers/distilbert-multilingual-nli-stsb-quora-ranking](url) adapting the chinese tutorial. Unfortunately, the process hangs, meaning fa_fsm2fsm_iwec seems to be stuck, moreover no error information received .

**Comment by stonor** [comment]
Hi RobertGengui,

You probably just need patience. When I build it takes between 5 hours and 4 days to finish.

**Comment by SergeiAlonichau** [comment]
Hi,

Did you try to use --no-min option in the options.small ?

...
opt_build_wbd = --dict-root=. --full-unicode **--no-min**
...
